# Generated by Django 3.2.6 on 2021-08-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
